// import { attributes, html } from "@content/test.md";
import React from "react";

export { Page };

function Page({ attributes, html}) {
  return (
    <>
      {/* BACKGROUND */}
      <div 
        display="flex"
        align="items-start"
        justify="center"
        bg="cool-gray-200"
        h="min-screen"
      >
        {/* BOX */}
        <div
          p="4"
          m="x-2 t-10 b-16 md:x-10"
          space="y-12"
          overflow="hidden"
          bg="gray-100"
          border="rounded-md"
          shadow="2xl"
          w="max-7xl"
        >
          {/* BOX CONTENT */}
          <div
            w="full max-5xl"
            space="y-12"
            p="md:x-20"
          >
            <section>
              <div 
                p="y-2"
                space="y-4"
                text="center"
              >
                <h2 
                  text="2xl md:4xl"
                  font="bold tracking-wide"
                >
                  { attributes.title }
                </h2>

                {/* <div v-if="content.value.skills" class="space-x-3">
                  <Pill
                    v-for="(skill, idx) in content.value.skills"
                    :key="idx"
                    :text="skill"
                  />
                </div> */}
                {/* <p class="text-xs text-gray-500 md:text-base">
                  <!--  {{ new Date(post.date).toLocaleDateString() }}-->
                </p> */}
              </div>

              <article
                w="max-3xl"
                p="x-1 md:x-0"
                m="x-auto t-4"
                text="prose justify"
                className="prose prose-lg"
                dangerouslySetInnerHTML={{__html: html}}
              >
                {/* <p>
                Spatial Analytical Science focuses on developing and applying ever-improving means of measuring and interpreting the composition, structure, and morphology of the spatial patterns and processes generated by natural and human systems. It is broadly concerned with characterizing places, such as regions, cities, and neighborhoods and the connections and relationships between them through the use of various technical approaches. Spatial analytical scientists use their knowledge of sensors, computation, statistics, and data science to understand and solve problems in almost all areas of society, including population health, transportation, disaster management, climate change, agriculture, and many more. And though spatial analysis usually targets phenomena at geographic scales - those that can be referenced and observed on the Earth’s surface - it is also relevant at more micro and macro scales too.
                </p> */}
                
                </article>
            </section>

            {/* <div
            class="
            flex flex-col
            items-center
            justify-around
            md:items-start md:flex-row
            "
            >
            <nuxt-link
            v-if="prev.value"
            :to="prev.value.path"
            class="
              flex flex-col
              items-center
              justify-around
              p-2
              space-y-1
              md:space-y-3
            "
            >
            <Icon
              icon="ic:outline-keyboard-arrow-left"
              class="flex-shrink-0 w-12 h-12 text-indigo-600"
              aria-hidden="true"
            />
            <div class="space-y-1 text-center">
              <p
                class="
                  hidden
                  overflow-hidden
                  font-semibold
                  text-center
                  break-normal
                  md:block
                "
                style="max-width: 12rem; max-height: 6rem"
              >
                {{ prev.value.title }}
              </p>
              <span class="text-xs text-gray-500 uppercase md:hidden"
                >Previous</span
              >
            </div>
            </a>

            <a
            v-if="next.value"
            :to="next.value.path"
            class="
              flex flex-col
              items-center
              justify-around
              p-2
              space-y-1
              md:space-y-3
            "
            >
            <Icon
              icon="ic:outline-keyboard-arrow-right"
              class="flex-shrink-0 w-12 h-12 text-indigo-600"
              aria-hidden="true"
            />
            <div class="space-y-1 text-center">
              <p
                class="
                  hidden
                  overflow-hidden
                  font-semibold
                  text-center
                  break-normal
                  md:block
                "
                style="max-width: 12rem; max-height: 6rem"
              >
                {{ next.value.title }}
              </p>
              <span class="text-xs text-gray-500 uppercase md:hidden"
                >Next</span
              >
            </div>
            </a>
            </div> */}
          </div>
        </div>
      </div>
    </>
  );
}