
[build]
    base = "tralka.xyz/"
    publish = "dist/client/"
    command = "npm run build:prerender"
[context.staging]
    command = "npm run build:prerender"
[[redirects]]
    from = "/admin"
    to = "/admin/index.html"
    force = true
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true