backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - label: 'Index Sections'
    name: 'index'
    files:
      - label: 'Card One'
        name: 'index-card-one'
        file: 'tralka.xyz/content/index/index-card-one.yml'
        fields:
          - label: Title
            name: titleOptions
            widget: list
            fields:
              - label: Option
                name: option
                widget: string
          - label: Subtitle
            name: subtitle
            widget: string
